
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Basket {
			/**
			* Session Address Book
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#130) 
			*/
			sessionAddressBook: string | null;

		}
		interface Category {
			/**
			* Alternative URL

				Renders an alternative URL in main navigation. Uses Salesforce Commerce Cloud content url notation. For example: $url('Account-Show')$ or normal URL http://xchange.demandware.com
			* @group customAttributes - Custom
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#334) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#460)
			*/
			alternativeUrl: MarkupText | null;

			/**
			* Category Banner ID

				Used to define the content asset used to populate a grid page banner for a category. This value is applied to all sub-category navigation (cascading) if no specific catBannerID has been defined for  a sub-category.
			* @group customAttributes - Custom
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#344) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#457)
			*/
			catBannerID: string | null;

			/**
			* Custom CSS File

				Use this attribute to apply custom styles for this category.
			* @group Presentation - Presentation Attributes
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#353) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#445)
			*/
			customCSSFile: MediaFile | null;

			/**
			* Enable Compare

				Used to define if/when the Compare feature is to be visualized in the storefront based on navigation. If enableCompare = FALSE, no Compare checkboxes will be displayed in the grid view. If enableCompare = TRUE, the category (and its children) will support the Compare feature.
			* @group customAttributes - Custom
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#361) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#456)
			*/
			enableCompare: boolean | null;

			/**
			* Header Menu Banner
			* @group customAttributes - Custom
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#368) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#459)
			*/
			headerMenuBanner: MarkupText | null;

			/**
			* Header Menu Orientation

				Which way to orient the menu and optional header menu HTML. Vertical will list all in one line. Horizontal will list in columns.
			* @group customAttributes - Custom
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#375) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#458)
			*/
			headerMenuOrientation: EnumValue<'Horizontal' | 'Vertical' | null> 

			/**
			* Show in Menu Navigation

				Used to indicate that a category (such as Mens -> Footwear -> Boots) will display in the roll-over navigation. A sub-category only shows if also the parent category is marked as showInMenu. Up to three category levels are shown in roll-over navigation.
			* @group customAttributes - Custom
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#393) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#455)
			*/
			showInMenu: boolean | null;

			/**
			* Size Chart

				Used to define the content asset ID of the Size Chart that is appropriate for products whose PRIMARY category is the associated category (and its children). Whenever a product detail page (or quick view) is rendered, the Size Chart link is populated based on the value of this attribute for the products primary categorization. If not defined, NO size chart link is displayed.
			* @group customAttributes - Custom
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#400) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#454)
			*/
			sizeChartID: string | null;

			/**
			* Slot Banner HTML
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#409) 
			*/
			slotBannerHtml: MarkupText | null;

			/**
			* Category Landing Slot Image

				Image used on either the top or bottom slot on the category landing pages.
			* @group Presentation - Presentation Attributes
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#416) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#444)
			*/
			slotBannerImage: MediaFile | null;

		}
		interface Content {
			/**
			* Year
			* @group Content - Content
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#568) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#625)
			*/
			Year: string | null;

			/**
			* Body
			* @group Content - Content
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#577) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#624)
			*/
			body: MarkupText | null;

			/**
			* Custom CSS File

				Use this attribute to apply custom styles for this content asset.
			* @group Presentation - Presentation
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#585) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#620)
			*/
			customCSSFile: MediaFile | null;

		}
		interface CustomerActiveData {
			/**
			* Returned items

				The number of items returned by this customer
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#710) 
			*/
			returnItems: number | null;

		}
		interface Folder {
			/**
			* Custom CSS File

				Use this attribute to apply custom styles for this category.
			* @group Presentation - Presentation
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#965) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#992)
			*/
			customCSSFile: MediaFile | null;

		}
		interface PaymentTransaction {
			/**
			* eFunds Transaction History
			* @group Custom - Custom
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#1662) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#1672)
			*/
			eFundsTransactionHistory: ReadonlyArray<string> 

		}
		interface Product {
			/**
			* Available for In Store Pickup

				Signals if there are inventory lists for brick-and-mortar stores associated with this product.
			* @group inStorePickup - In Store Pickup
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#1983) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3359)
			*/
			availableForInStorePickup: boolean | null;

			/**
			* Battery Life
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#1994) 
			*/
			batteryLife: string | null;

			/**
			* Battery Type
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2006) 
			*/
			batteryType: string | null;

			/**
			* Boot Type

				Type of Boot for search refinement.
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2018) 
			*/
			bootType: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070'>> 

			/**
			* Bottom Type

				Bottom type for search refinement
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2061) 
			*/
			bottomType: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080'>> 

			/**
			* Color

				Product color used for variation attribute
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2108) 
			*/
			color: string | null;

			/**
			* Extended Warranty
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2121) 
			*/
			consoleWarranty: string | null;

			/**
			* Custom CSS File

				Use this attribute to apply custom styles for this product.
			* @group Presentation - Presentation Attributes
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2133) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3341)
			*/
			customCSSFile: MediaFile | null;

			/**
			* Digital Camera Features
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2145) 
			*/
			digitalCameraFeatures: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | '0090' | '0100' | '0110' | '0120' | '0130' | '0140' | '0150' | '0160' | '0170' | '0180' | '0190' | '0200' | '0210' | '0220' | '0230' | '0240' | '0250' | '0260' | '0270' | '0280'>> 

			/**
			* Digital Camera Pixels
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2271) 
			*/
			digitalCameraPixels: string | null;

			/**
			* Digital Camera Type
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2283) 
			*/
			digitalCameraType: string | null;

			/**
			* Extended Warranty
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2295) 
			*/
			digitalCameraWarranty: string | null;

			/**
			* Depth
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2307) 
			*/
			dimDepth: string | null;

			/**
			* Height
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2319) 
			*/
			dimHeight: string | null;

			/**
			* Weight
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2331) 
			*/
			dimWeight: string | null;

			/**
			* Width
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2343) 
			*/
			dimWidth: string | null;

			/**
			* Display Size
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2355) 
			*/
			displaySize: string | null;

			/**
			* Genre
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2367) 
			*/
			gameGenre: ReadonlyArray<EnumValue<'Action' | 'Educational' | 'Kids' | 'Racing' | 'Role-Playing' | 'Sports' | 'Strategy'>> 

			/**
			* Game Rating
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2409) 
			*/
			gameRating: string | null;

			/**
			* Gaming System
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2421) 
			*/
			gameSystemType: string | null;

			/**
			* GPS Features
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2433) 
			*/
			gpsFeatures: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | '0090' | '0100' | '0110' | '0120' | '0130' | '0140' | '0150' | '0160' | '0170' | '0180' | '0190' | '0200' | '0210' | '0230'>> 

			/**
			* GPS Type
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2535) 
			*/
			gpsType: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040'>> 

			/**
			* Extended Warranty
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2565) 
			*/
			gpsWarranty: string | null;

			/**
			* Image Aspect Ratio
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2577) 
			*/
			imageAspectRatio: string | null;

			/**
			* New Arrival?
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2589) 
			*/
			isNew: boolean | null;

			/**
			* New Arrival?

				This indiciates if the product is a new arrival.
			* @group searchRefinements - Search Refinements
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2599) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3370)
			*/
			isNewtest: boolean | null;

			/**
			* On sale?

				This is the help text. It is used for sorting rules.
			* @group searchRefinements - Search Refinements
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2610) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3372)
			*/
			isSale: boolean | null;

			/**
			* Age

				Kids Age used for search refinements
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2621) 
			*/
			kidsAge: EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | null> 

			/**
			* Length

				This attribute is used for mens and womens pants lengths.
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2663) 
			*/
			length: string | null;

			/**
			* Lens Aperture
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2676) 
			*/
			lensAperture: string | null;

			/**
			* Material
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2688) 
			*/
			materialTest: ReadonlyArray<EnumValue<'cotton' | 'wool' | 'polyester'>> 

			/**
			* Media Format

				Media Format
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2714) 
			*/
			mediaFormat: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | '0090' | '0100'>> 

			/**
			* Memory Size

				Memory Size
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2769) 
			*/
			memorySize: string | null;

			/**
			* Memory Type
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2782) 
			*/
			memoryType: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | '0090'>> 

			/**
			* Music Storage
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2832) 
			*/
			musicStorage: string | null;

			/**
			* Optical Zoom
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2844) 
			*/
			opticalZoom: string | null;

			/**
			* Outerwear Type

				Type of Outerwear for search refinement
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2856) 
			*/
			outerwearType: EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | null> 

			/**
			* Portable Audio Type
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2902) 
			*/
			portableAudioType: ReadonlyArray<EnumValue<'0010' | '0020' | '0030'>> 

			/**
			* Refinement Color
			* @group storefrontAttributes - Storefront Attributes
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2928) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3365)
			*/
			refinementColor: EnumValue<'black' | 'blue' | 'green' | 'red' | 'orange' | 'pink' | 'purple' | 'white' | 'yellow' | 'grey' | 'beige' | 'miscellaneous' | 'brown' | 'navy' | null> 

			/**
			* Resolution
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#2997) 
			*/
			resolution: string | null;

			/**
			* Sandal Type

				Type of Sandal for search refinement
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3009) 
			*/
			sandalType: EnumValue<'0010' | '0020' | '0030' | null> 

			/**
			* Sheets

				test attribute
			* @group searchRefinements - Search Refinements
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3035) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3371)
			*/
			sheets: ReadonlyArray<EnumValue<'value1' | 'value2' | 'value3'>> 

			/**
			* Shoe Type

				Type of Shoe for search refinements
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3062) 
			*/
			shoeType: EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | '0090' | '0100' | '0110' | null> 

			/**
			* Size

				This attribute is used for all footwear, apparel and accessory sizing for men, women and kids products.
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3120) 
			*/
			size: string | null;

			/**
			* Skin Concern
			* @group searchRefinements - Search Refinements
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3133) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3369)
			*/
			skinConcern: ReadonlyArray<EnumValue<'dryTight' | 'comprehensive' | 'liftingLossFirm'>> 

			/**
			* Style Number
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3159) 
			*/
			styleNumber: string | null;

			/**
			* Description
			* @group storefrontAttributes - Storefront Attributes
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3172) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3363)
			*/
			tabDescription: MarkupText | null;

			/**
			* Details
			* @group storefrontAttributes - Storefront Attributes
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3183) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3364)
			*/
			tabDetails: MarkupText | null;

			/**
			* test
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3194) 
			*/
			test: MarkupText | null;

			/**
			* Top Type

				Type of tops in clothing
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3206) 
			*/
			topType: EnumValue<null> 

			/**
			* TV Signal Format
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3218) 
			*/
			tvSignalFormat: string | null;

			/**
			* Size
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3230) 
			*/
			tvSize: string | null;

			/**
			* TV Type
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3242) 
			*/
			tvType: EnumValue<'0010' | '0020' | '0030' | '0040' | null> 

			/**
			* Extended Warranty
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3271) 
			*/
			tvWarranty: string | null;

			/**
			* Video Storage
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3283) 
			*/
			videoStorage: string | null;

			/**
			* Waist

				Attribute used for apparel waist sizing.
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3295) 
			*/
			waist: string | null;

			/**
			* Width

				This attribute is used for shoe widths for mens, womens and kids.
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3308) 
			*/
			width: string | null;

		}
		interface ProductLineItem {
			/**
			* From Store ID

				Links the store to the product line item for grouping shipments in the checkout process.
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3546) 
			*/
			fromStoreId: string | null;

		}
		interface Profile {
			/**
			* Family Status
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#3734) 
			*/
			familyStatus: EnumValue<null> 

		}
		interface Shipment {
			/**
			* Pickup Store ID

				Used to map the shipment to a  brick and mortar store.
			* @group storepickup - Store Pickup Information
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4144) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4173)
			*/
			fromStoreId: string | null;

			/**
			* When this attribute equals 'instore', the checkout flow will assign the shipping method (005) which has a no shipping charge.
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4153) 
			*/
			shipmentType: string | null;

			/**
			* Store Pickup Message

				This is text used by the end user when sending a message to the brick and mortar store about the shipment.  This is reflected in the order export.
			* @group storepickup - Store Pickup Information
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4160) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4174)
			*/
			storePickupMessage: string | null;

		}
		interface ShippingMethod {
			/**
			* Store Pickup Enabled
			* @group storePickUp - Store Pick Up
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4212) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4222)
			*/
			storePickupEnabled: boolean | null;

		}
		interface SitePreferences {
			/**
			* GoogleVerificationTag - Content Attribute
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4308) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4579)
			*/
			GoogleVerificationTag: string | null;

			/**
			* Build Notification Email List

				Semicolon separated list
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4315) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4580)
			*/
			buildNotificationEmailList: string | null;

			/**
			* Check TLS

				When true, this causes a TLS check to take place based on whether or not a cookie ('dw_TLSWarning') has been set on the browser
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4323) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4590)
			*/
			checkTLS: boolean | null;

			/**
			* Default Country Code

				Default country code for store searches
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4331) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4585)
			*/
			countryCode: EnumValue<'US' | 'CA' | null> 

			/**
			* Customer Service Email
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4348) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4588)
			*/
			customerServiceEmail: string | null;

			/**
			* Disable Responsive Design

				Disable Responsive Design for Storefront
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4357) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4578)
			*/
			disableResponsiveDesign: boolean | null;

			/**
			* Enable Infinite Scroll

				This Boolean toggles the option for infinite scrolling or pagination from within the search grid.
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4365) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4582)
			*/
			enableInfiniteScroll: boolean | null;

			/**
			* Enable MultiShipping

				The attribute is used to enable/disable Multi-Shipment Checkout for each site via BM.
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4373) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4583)
			*/
			enableMultiShipping: boolean | null;

			/**
			* Enable In Store Pickup

				This Boolean enables the storefront ability to perform tasks related to in store orders
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4381) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4584)
			*/
			enableStorePickUp: boolean | null;

			/**
			* Default List Price Book ID
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4389) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4577)
			*/
			listPriceDefault: string | null;

			/**
			* Rate Limiter Threshold

				This number indicates the number of times failures for Logins, GiftCert Balances, and Order Tracking requests will be allowed before displaying a CAPTCHA-style pop-up rate limiter
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4397) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4589)
			*/
			rateLimiterThreshold: number | null;

			/**
			* Slide Slow effect

				Please visit http://jquery.malsup.com/cycle/browser.html for complete visual effects
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4406) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4581)
			*/
			slideshoweffect: EnumValue<'blindX' | 'blindY' | 'blindZ' | 'cover' | 'curtainX' | 'curtainY' | 'fade' | 'fadeZoom' | 'growX' | 'growY' | 'none' | 'scrollUp' | 'scrollDown' | 'scrollLeft' | 'scrollRight' | 'scrollHorz' | 'scrollVert' | 'shuffle' | 'slideX' | 'slideY' | 'toss' | 'turnUp' | 'turnDown' | 'turnLeft' | 'turnRight' | 'uncover' | 'wipe' | 'zoom' | null> 

			/**
			* Store Lookup Max Distance

				Store Lookup Max Distance
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4527) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4587)
			*/
			storeLookupMaxDistance: EnumValue<50 | 75 | 100 | 150 | 200 | null> 

			/**
			* Store Lookup Unit

				Used in finding the store near the ZIP code specified in the storefront by the end user.
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4556) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4586)
			*/
			storeLookupUnit: EnumValue<'km' | 'mi' | null> 

		}
		interface Store {
			/**
			* Test Attribute
			* 
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4731) 
			*/
			TestAttribute: ReadonlyArray<string> 

			/**
			* Country Code Value

				Country Code Value - for the form values
			* @group Address - Address
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4739) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4769)
			*/
			countryCodeValue: string | null;

			/**
			* Store Inventory List ID

				Store Inventory List ID
			* @group Inventory - Inventory
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4748) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4773)
			*/
			inventoryListId: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* GoogleVerificationTag - Content Attribute
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4308) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4579)
			*/
			(name: 'GoogleVerificationTag'): string | null;
			
			/**
			* Build Notification Email List

				Semicolon separated list
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4315) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4580)
			*/
			(name: 'buildNotificationEmailList'): string | null;
			
			/**
			* Check TLS

				When true, this causes a TLS check to take place based on whether or not a cookie ('dw_TLSWarning') has been set on the browser
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4323) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4590)
			*/
			(name: 'checkTLS'): boolean | null;
			
			/**
			* Default Country Code

				Default country code for store searches
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4331) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4585)
			*/
			(name: 'countryCode'): EnumValue<'US' | 'CA' | null> 
			
			/**
			* Customer Service Email
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4348) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4588)
			*/
			(name: 'customerServiceEmail'): string | null;
			
			/**
			* Disable Responsive Design

				Disable Responsive Design for Storefront
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4357) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4578)
			*/
			(name: 'disableResponsiveDesign'): boolean | null;
			
			/**
			* Enable Infinite Scroll

				This Boolean toggles the option for infinite scrolling or pagination from within the search grid.
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4365) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4582)
			*/
			(name: 'enableInfiniteScroll'): boolean | null;
			
			/**
			* Enable MultiShipping

				The attribute is used to enable/disable Multi-Shipment Checkout for each site via BM.
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4373) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4583)
			*/
			(name: 'enableMultiShipping'): boolean | null;
			
			/**
			* Enable In Store Pickup

				This Boolean enables the storefront ability to perform tasks related to in store orders
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4381) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4584)
			*/
			(name: 'enableStorePickUp'): boolean | null;
			
			/**
			* Default List Price Book ID
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4389) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4577)
			*/
			(name: 'listPriceDefault'): string | null;
			
			/**
			* Rate Limiter Threshold

				This number indicates the number of times failures for Logins, GiftCert Balances, and Order Tracking requests will be allowed before displaying a CAPTCHA-style pop-up rate limiter
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4397) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4589)
			*/
			(name: 'rateLimiterThreshold'): number | null;
			
			/**
			* Slide Slow effect

				Please visit http://jquery.malsup.com/cycle/browser.html for complete visual effects
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4406) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4581)
			*/
			(name: 'slideshoweffect'): EnumValue<'blindX' | 'blindY' | 'blindZ' | 'cover' | 'curtainX' | 'curtainY' | 'fade' | 'fadeZoom' | 'growX' | 'growY' | 'none' | 'scrollUp' | 'scrollDown' | 'scrollLeft' | 'scrollRight' | 'scrollHorz' | 'scrollVert' | 'shuffle' | 'slideX' | 'slideY' | 'toss' | 'turnUp' | 'turnDown' | 'turnLeft' | 'turnRight' | 'uncover' | 'wipe' | 'zoom' | null> 
			
			/**
			* Store Lookup Max Distance

				Store Lookup Max Distance
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4527) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4587)
			*/
			(name: 'storeLookupMaxDistance'): EnumValue<50 | 75 | 100 | 150 | 200 | null> 
			
			/**
			* Store Lookup Unit

				Used in finding the store near the ZIP code specified in the storefront by the end user.
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4556) | [group](file:c:\Users\gaggi\Documents\Workspaces\Workspace VS\SFRA_Collettivo\sitegenesis-master\demo_data_no_hires_images\meta\system-objecttype-extensions.xml#4586)
			*/
			(name: 'storeLookupUnit'): EnumValue<'km' | 'mi' | null> 
			
	}
}